"""Initial Schema

Revision ID: d769d4cb15f6
Revises: 
Create Date: 2026-07-10 21:48:58.463501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd769d4cb15f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('financial_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year_month', sa.String(), nullable=False),
    sa.Column('gst_turnover', sa.Float(), nullable=True),
    sa.Column('upi_inflow', sa.Float(), nullable=True),
    sa.Column('bank_inflow', sa.Float(), nullable=True),
    sa.Column('bank_outflow', sa.Float(), nullable=True),
    sa.Column('bank_avg_balance', sa.Float(), nullable=True),
    sa.Column('bank_min_balance', sa.Float(), nullable=True),
    sa.Column('bank_bounce_incidents', sa.Integer(), nullable=True),
    sa.Column('bank_low_balance_months', sa.Integer(), nullable=True),
    sa.Column('bank_od_cc_utilized', sa.Float(), nullable=True),
    sa.Column('epfo_contributions', sa.Float(), nullable=True),
    sa.Column('epfo_employee_count', sa.Integer(), nullable=True),
    sa.Column('utility_monthly_units', sa.Integer(), nullable=True),
    sa.Column('utility_payment_regularity', sa.Float(), nullable=True),
    sa.Column('utility_disconnection_events', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_data_user_id'), 'financial_data', ['user_id'], unique=False)
    op.create_index(op.f('ix_financial_data_year_month'), 'financial_data', ['year_month'], unique=False)
    op.create_table('loan_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applications_user_id'), 'loan_applications', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('employee_id_code', sa.String(), nullable=True),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('aadhaar', sa.String(), nullable=True),
    sa.Column('vintage', sa.String(), nullable=True),
    sa.Column('employees_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_employee_id_code'), 'profiles', ['employee_id_code'], unique=True)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_application_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('cash_flow_score', sa.Integer(), nullable=False),
    sa.Column('revenue_score', sa.Integer(), nullable=False),
    sa.Column('compliance_score', sa.Integer(), nullable=False),
    sa.Column('operations_score', sa.Integer(), nullable=False),
    sa.Column('resilience_score', sa.Integer(), nullable=False),
    sa.Column('risk_category', sa.String(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('cross_val_divergence', sa.Float(), nullable=True),
    sa.Column('cross_val_flagged', sa.Boolean(), nullable=True),
    sa.Column('underwriter_note', sa.Text(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_loan_application_id'), 'scores', ['loan_application_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_loan_application_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_employee_id_code'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_loan_applications_user_id'), table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_index(op.f('ix_financial_data_year_month'), table_name='financial_data')
    op.drop_index(op.f('ix_financial_data_user_id'), table_name='financial_data')
    op.drop_table('financial_data')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
